import{a as w,S as b,i}from"./assets/vendor-73qhTu8_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();const v="https://pixabay.com/api/",S="55656365-3c91dbda272652fb6677c72ed";async function d(o,t){const{data:r}=await w(v,{params:{key:S,q:o,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}});return r}const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),q=new b(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(r=>`
<li class="gallery-item">
  <a href="${r.largeImageURL}">
    <img src="${r.webformatURL}" alt="${r.tags}" />
  </a>
  <div class="info">
    <p>Likes: ${r.likes}</p>
    <p>Views: ${r.views}</p>
    <p>Comments: ${r.comments}</p>
    <p>Downloads: ${r.downloads}</p>
  </div>
</li>`).join("");u.insertAdjacentHTML("beforeend",t),q.refresh()}function B(){u.innerHTML=""}function h(){f.classList.remove("hidden")}function p(){f.classList.add("hidden")}function E(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}const M=document.querySelector(".form"),P=document.querySelector(".load-more");let n=1,s="";const L=15;M.addEventListener("submit",async o=>{if(o.preventDefault(),s=o.target.elements["search-text"].value.trim(),!!s){n=1,B(),g(),h();try{const t=await d(s,n);if(!t.hits.length){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(t.hits),t.totalHits>L&&E()}catch{i.error({title:"Error",message:"Something went wrong. Try again later."})}finally{p()}}});P.addEventListener("click",async()=>{n+=1,h();try{const o=await d(s,n);y(o.hits);const t=Math.ceil(o.totalHits/L);n>=t&&(g(),i.info({message:"We're sorry, but you've reached the end of search results."}));const r=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"})}catch{i.error({title:"Error",message:"Something went wrong. Try again later."})}finally{p()}});
//# sourceMappingURL=index.js.map
