import{a as b,S as v,i as n}from"./assets/vendor-73qhTu8_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))m(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const u of a.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&m(u)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function m(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();const S="https://pixabay.com/api/",P="55656365-3c91dbda272652fb6677c72ed";async function y(o,t){const{data:r}=await b(S,{params:{key:P,q:o,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}});return r}const c=document.querySelector(".gallery"),l=document.querySelector(".loader"),d=document.querySelector(".load-more"),q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){if(!c)return;const t=o.map(r=>`
<li class="gallery-item">
  <a href="${r.largeImageURL}">
    <img src="${r.webformatURL}" alt="${r.tags}" />
  </a>
  <div class="info">
    <p>Likes: ${r.likes}</p>
    <p>Views: ${r.views}</p>
    <p>Comments: ${r.comments}</p>
    <p>Downloads: ${r.downloads}</p>
  </div>
</li>`).join("");c.insertAdjacentHTML("beforeend",t),q.refresh()}function M(){c&&(c.innerHTML="")}function g(){l&&l.classList.remove("hidden")}function p(){l&&l.classList.add("hidden")}function L(){d&&d.classList.remove("hidden")}function f(){d&&d.classList.add("hidden")}const B=document.querySelector(".form"),E=document.querySelector(".load-more");let s=1,i="";const w=15;B.addEventListener("submit",async o=>{if(o.preventDefault(),i=o.target.elements["search-text"].value.trim(),!!i){s=1,M(),f(),g();try{const t=await y(i,s);if(!t.hits.length){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}h(t.hits),Math.ceil(t.totalHits/w)>1?L():n.info({message:"We're sorry, but you've reached the end of search results."})}catch{n.error({title:"Error",message:"Something went wrong. Try again later."})}finally{p()}}});E.addEventListener("click",async()=>{s+=1,f(),g();try{const o=await y(i,s);h(o.hits);const t=Math.ceil(o.totalHits/w);s>=t?(f(),n.info({message:"We're sorry, but you've reached the end of search results."})):L();const r=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"})}catch{n.error({title:"Error",message:"Something went wrong. Try again later."})}finally{p()}});
//# sourceMappingURL=index.js.map
